
stages:
  - build
  - cleanup

before_script:
  - export src_dir=${CI_PROJECT_DIR}
  - export git_hash=${CI_COMMIT_SHA:0:6}
  - export build_dir="${CI_PROJECT_DIR}-sb-${git_hash}"
  - hostname
  - whoami
  - pwd
  - echo "Sources - ${src_dir}"
  - echo "Commit - ${git_hash}"
  - echo "Build - ${build_dir}"


Mac build:

  stage: build

  script:
    - mkdir -p ${build_dir}
    - cd ${build_dir}
    - cmake -DBUILD_QOpenGLDemo:BOOL=TRUE
          -DCMAKE_PREFIX_PATH:PATH=/usr/local/opt/qt5
          -DBUILD_TESTING:BOOL=ON
          ${src_dir}
    - make -j 1

  tags:
    - gift-mac


Mac cleanup:

  stage: cleanup

  script:
    - export sb_dir="${sb_dir:0:${#sb_dir}-1}R"
    - rm -rf ${sb_dir}

  when: always

  only:
    - tags

  tags:
    - gift-mac
